### ISSUE TITLE
Add directory creation

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud-client#10]

**Comment by riesinger** [comment]
I have a PR coming Sunday for this:wink:

**Comment by riesinger** [comment]
Note that this will not work correctly in sub-directories deeper than level 1 (if 0 is the root), because of [freecloud#97](https://github.com/freecloudio/freecloud/issues/97)

**Comment by TheHamloer** [comment]
Because of this we probably should work on implementing the file info in the database...

**Comment by riesinger** [comment]
Yeah maybe, but we can strip the path nonetheless
