### ISSUE TITLE
Implement typescript

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud-client#21]
While developing directory creation, I started to notice that I had problems accessing properties of objects which didn't exist. I think we can circumvent that by switching to typescript.

There's also a great tool which converts go structs to typescript models: [see it here](https://github.com/tkrajina/typescriptify-golang-structs)

@TheHamloer, what do you think of this idea?

**Comment by TheHamloer** [comment]
I think that would be a great idea! That way we can ensure that the front- and backend are talking about the same stuff :+1:

**Comment by riesinger** [comment]
Great 👍 I will do this right after publishing the directory creation.

**Comment by riesinger** [comment]
I am currently trying to convert Vuex to Typescript, which proves to be not exactly trivial. While procrastinating, I got a rather stupid idea: @TheHamloer What do you think of this project being converted to GopherJS? 😂 There are some [bindings for VueJS available](https://github.com/oskca/gopherjs-vue) and you could contribute to the frontend without learning Vue 😂

**Comment by TheHamloer** [comment]
In general why not 😂 I'm just thinking if we run into problems there too... This combination is not really normal. Also wouldn't it be possible to have vuex in pure javascript?

**Comment by riesinger** [comment]
This was just a joke idea, I think we should continue using typescript. However, if we are not typing the store, typescript would be pretty useless, as this is one of the main areas of mistakes happening. I have luckily found a course on typescript with vuex on egghead.io, but I have to subscribe to view it throughout. 
I have already started working on the typescript store though 🚀

**Comment by TheHamloer** [comment]
👍 and also it's a good reason to learn vujs 😄

**Comment by riesinger** [comment]
I just pushed the first working version. However, there are some things that I need to do, before this effort is finished:

- [ ] Add tslint rules
- [ ] Figure out whether we need Babel anymore, and if not, remove it from the project
- [ ] Lots and lots of cleanup
- [ ] Write models for `File`
- [ ] Find a way to access typed getters from the router (this is not merge-blocking, as it is seldomly used)

**Comment by riesinger** [comment]
I still have no idea for the last point in the checklist above, however, this is a rare case, so I think we shouldn't care for now and come back once we get more experienced with TypeScript and Vuex
