### ISSUE TITLE
Move away from SFC's

### ISSUE THREAD

**Issue by riesinger** [freecloudio/freecloud-client#24]
We currently use Single File Components (SFCs) everywhere. These are great, considering, that you only have to edit one file at a time. However, those also have one huge drawback: **Editor Support**.

While VSCode handles SFCs as best as it gets, it's not like the *full* VSCode-TypeScript-Glory there usually is when editing `.ts` files. Also, handling of TSLint vs ESLint in `.vue` files is *really* janky, as both lint them sometimes, neither one does always... It's a mess!

Therefore, I think it would be a good solution to split SFCs into a `<componentName>.vue` and a `<componentName>.ts` file. This would leverage better tooling, as well as make files smaller for more complex components.
However, I *do not* suggest splitting components like PageNotFound into two files, this would be utterly useless.

**Comment by TheHamloer** [comment]
I agree 👍
Choosing whether to split a component up or not should be decided by human logic 😅

**Comment by riesinger** [comment]
Actually I wrote a script generating component boilerplate, therefore, I refactored every component:joy:

**Comment by riesinger** [comment]
This has been closed by #28
