### ISSUE TITLE
Wrong directory shown in file preview background

### ISSUE THREAD

**Issue by mheidinger** [freecloudio/freecloud-client#53]
You can see this behavior when opening a file preview in a subfolder: It opens the preview and in the background you can see the root directory.

**Comment by riesinger** [comment]
Edited the title from "Directory page gets redrawn when opening a file preview" to "Wrong directory shown in file preview background", as the directory page actualy **must** get redrawn (we change the route, so we change the mounted components)

**Comment by TheHamloer** [comment]
Okay and there is no other solution to this? Because a redraw also means a new GET-request that is unnecessary...
